INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_PARTNER_LIST_VIEW', 'Partners', '/partner/list');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_CUSTOMER_LIST_VIEW', 'Customers', '/customer/list');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_SINGLE_AIRTIME', 'Airtime', '/airtime/singleAirtime');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_BULK_AIRTIME', 'Bulk airtime', '/airtime/bulkAirtime');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_TRANSACTION_LIST_VIEW', 'Transactions', '/transaction/filter');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_SINGLE_BANK_TRANSFER', 'Single bank transfer', '/banktransfer/single');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_BULK_BANK_TRANSFER', 'Bulk bank transfer', '/banktransfer/bulk');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_PROPERTY_LIST_VIEW', 'Properties', '/property/list');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_CARDLESS_ATM_CASHOUT', 'Cardless ATM cashout', '/cardlessatmcashout/single');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_BULK_CARDLESS_ATM_CASHOUT', 'Bulk cardless ATM cashout', '/cardlessatmcashout/bulk');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_SINGLE_ISSUE_AND_LOAD_CARDS', 'Load and issue cards', '/load/singleLoadAndIssueCards');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_BULK_ISSUE_AND_LOAD_CARDS', 'Bulk load and issue cards', '/load/bulkLoadAndIssueCards');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_SINGLE_LOAD_CARDS', 'Load cards', '/load/singleLoadCards');
INSERT INTO menu(category, role, title, url) VALUES ('ADMIN', 'ROLE_BULK_LOAD_CARDS', 'Bulk load cards', '/load/bulkLoadCards');